name: Expo Publish with AWS environment dev
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish Expo with AWS environment dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: expo setup
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-packager: npm

      - name: amplify setup, dev
        run: |
          npm install --global --unsafe-perm @aws-amplify/cli
          amplify pull --amplify \
          "{\"appId\":\"d32twf9usoa242\", \
          \"envName\":\"dev\"}" \
          --providers \
          "{\"awscloudformation\": \
          {\"configLevel\":\"project\", \
          \"useProfile\":false, \
          \"accessKeyId\":\"$AWS_ACCESS_KEY_ID\", \
          \"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\", \
          \"region\":\"$AWS_REGION\"} \
          }" \
          --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        working-directory: ./frontend

      - name: expo publish with aws
        run: |
          npm ci
          expo publish
        env:
          EXPO_USE_DEV_SERVER: true
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: ./frontend