
name: Test
 
on:
  pull_request:
    branches: 
      - main
      - frontend
      - backend

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm ci
          npm run test
        working-directory: ./frontend
        
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm ci
          npm run test
        working-directory: ./backend
